version: "3.7"

services:
  app:
    container_name: "fritzab2matrix"
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    entrypoint: ./fritzab2matrix.py
    volumes:
      - ../.:/app


      
      
  
